In [3]:
!pip install import-ipynb

You should consider upgrading via the '/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [6]:
# Import libraries
import import_ipynb
import Model
import pandas as pd
import numpy as np
import keras
import lightgbm as lgbm
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, recall_score, confusion_matrix, precision_score, f1_score

In [7]:
# Import dataset
df = pd.read_csv('data/input.csv')
df2 = df[['transaction_risk_score','cc_amount','ledger_balance','cardholder_presence','card_presence',
          'partial_approval_capable','channel','processing_type','date','cc_acceptor_state','cc_acceptor_country','is_fraud']]
df2 = df2.sort_values(by='date')
df2 = df2.drop("date",axis=1)

In [8]:
Model.GeneralSplit(df2,.8,'RandomForest')

-----RandomForest-----
Size of train set:  (28565, 10)
Size of test set:  (7142, 10)

Confusion-matrix: 
[[6741    1]
 [   0  400]]

Classification-report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6742
           1       1.00      1.00      1.00       400

    accuracy                           1.00      7142
   macro avg       1.00      1.00      1.00      7142
weighted avg       1.00      1.00      1.00      7142



In [9]:
Model.GeneralSplit(df2,.8,'LightGBM')

-----LightGBM-----
Size of train set:  (28565, 10)
Size of test set:  (7142, 10)

Confusion-matrix: 
[[6736    6]
 [   0  400]]

Classification-report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6742
           1       0.99      1.00      0.99       400

    accuracy                           1.00      7142
   macro avg       0.99      1.00      1.00      7142
weighted avg       1.00      1.00      1.00      7142



In [10]:
X = df2.drop("is_fraud",axis=1)
y = df2[['is_fraud']].values.flatten()
scalar = StandardScaler()
X_scale = scalar.fit_transform(X)

In [13]:
Model.TimeSeriesKFold(X, y, 10, 'RandomForest')

-----RandomForest-----
Size of data set:  (35707, 10)
Size of each fold:  3570

Splitting the first 2 chunks with ratio 1:1
Size of train + test:  (7140, 10)
Precision on fold 2:  0.971
Recall on fold 2:  0.85
Accuracy on fold 2:  0.99
F1_score on fold 2:  0.907
Confusion-matrix: 
[[3364    5]
 [  30  170]]

Splitting the first 3 chunks with ratio 2:1
Size of train + test:  (10710, 10)
Precision on fold 3:  1.0
Recall on fold 3:  0.835
Accuracy on fold 3:  0.989
F1_score on fold 3:  0.91
Confusion-matrix: 
[[3338    0]
 [  38  193]]

Splitting the first 4 chunks with ratio 3:1
Size of train + test:  (14280, 10)
Precision on fold 4:  0.984
Recall on fold 4:  0.79
Accuracy on fold 4:  0.99
F1_score on fold 4:  0.876
Confusion-matrix: 
[[3410    2]
 [  33  124]]

Splitting the first 5 chunks with ratio 4:1
Size of train + test:  (17850, 10)
Precision on fold 5:  0.992
Recall on fold 5:  0.746
Accuracy on fold 5:  0.988
F1_score on fold 5:  0.851
Confusion-matrix: 
[[3399    1]
 [  43  126

[array([0.971, 1.   , 0.984, 0.992, 0.96 , 0.994, 1.   , 1.   , 0.996]),
 array([0.85 , 0.835, 0.79 , 0.746, 0.95 , 0.893, 1.   , 1.   , 1.   ]),
 array([0.99 , 0.989, 0.99 , 0.988, 0.997, 0.994, 1.   , 1.   , 1.   ]),
 array([0.907, 0.91 , 0.876, 0.851, 0.955, 0.941, 1.   , 1.   , 0.998])]

In [14]:
Model.TimeSeriesKFold(X, y, 10, 'LightGBM')

-----LightGBM-----
Size of data set:  (35707, 10)
Size of each fold:  3570

Splitting the first 2 chunks with ratio 1:1
Size of train + test:  (7140, 10)
Precision on fold 2:  0.961
Recall on fold 2:  0.87
Accuracy on fold 2:  0.991
F1_score on fold 2:  0.913
Confusion-matrix: 
[[3362    7]
 [  26  174]]

Splitting the first 3 chunks with ratio 2:1
Size of train + test:  (10710, 10)
Precision on fold 3:  0.985
Recall on fold 3:  0.84
Accuracy on fold 3:  0.989
F1_score on fold 3:  0.907
Confusion-matrix: 
[[3335    3]
 [  37  194]]

Splitting the first 4 chunks with ratio 3:1
Size of train + test:  (14280, 10)
Precision on fold 4:  0.984
Recall on fold 4:  0.803
Accuracy on fold 4:  0.991
F1_score on fold 4:  0.884
Confusion-matrix: 
[[3410    2]
 [  31  126]]

Splitting the first 5 chunks with ratio 4:1
Size of train + test:  (17850, 10)
Precision on fold 5:  0.969
Recall on fold 5:  0.74
Accuracy on fold 5:  0.987
F1_score on fold 5:  0.839
Confusion-matrix: 
[[3396    4]
 [  44  125

[array([0.961, 0.985, 0.984, 0.969, 0.907, 0.994, 0.993, 0.991, 0.99 ]),
 array([0.87 , 0.84 , 0.803, 0.74 , 0.49 , 0.866, 1.   , 1.   , 1.   ]),
 array([0.991, 0.989, 0.991, 0.987, 0.984, 0.993, 1.   , 1.   , 0.999]),
 array([0.913, 0.907, 0.884, 0.839, 0.636, 0.926, 0.997, 0.996, 0.995])]